name: generar-noticias-oficiales

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Secret check
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: |
          if [ -z "$SERPAPI_API_KEY" ]; then
            echo "SERPAPI_API_KEY NO está disponible para el job"
            exit 1
          fi
          echo "SERPAPI_API_KEY está presente"
          python -c 'import os; print("Longitud del secret vista por Python:", len(os.getenv("SERPAPI_API_KEY","")))'

      - name: Run generator
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: |
          test -f scripts/generar_jsons.py || (echo "Falta scripts/generar_jsons.py"; ls -la; exit 1)
          python scripts/generar_jsons.py

      - name: Commit & push JSON
        run: |
          git config user.name  "actions-bot"
          git config user.email "actions@github.com"
          git add noticias/*.json || true
          git commit -m "news(oficiales): $(date -u +%F)" || echo "No changes"
          git push
